### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by markcmiller86** [joaomlneto/cpds-heat#9]
- How is this code licensed?
- How much has changed in Cuda, OpenMP and MPI in the last 5 years that would make re-coding these examples essential to stay so they are up to date with current standards?

**Comment by joaomlneto** [comment]
Hi @markcmiller86 ! Thanks for the interest 😃 

> How is this code licensed?

Me and Fotis (the students) are OK licensing this using MIT license (or any other permissive license). However, I have also forwarded the question to the [UPC](https://www.upc.edu/ca)/[BSC](https://www.bsc.es) professors who taught the course:
- [José Ramón Herrero](http://people.ac.upc.edu/josepr/)
- [Jordi Guitart Fernandez](https://www.bsc.es/guitart-fernandez-jordi)
- [Jorge Castro Rabal](https://futur.upc.edu/JorgeCastroRabal)
- [Joaquin Gabarro Valles](https://futur.upc.edu/JoaquinGabarroValles)

In case there are no objections, it'll be MIT over the next few days.

> How much has changed in CUDA, OpenMP and MPI

- I haven't used CUDA since, so I can't say for sure. The current code *may* not even be 100% working, as per #3, and I don't have a CUDA-enabled card to even test it.
- I believe there is nothing new in OpenMP that significantly affects performance. Maybe using *tasks* (à là [OmpSs](https://pm.bsc.es/ompss)) 
- The newer MPI standards may have some newer features that *may* result in significant improvements, as I believe there are newer ways of reducing synchronization overheads, but I can't say for sure!

I haven't been a big user of these frameworks in the past few years :)

However, I'd like to do basic maintenance on this code to (1) make it current and (2) make it work properly. In case you encounter any issues, please do let us know and we'll try to fix it!

**Comment by markcmiller86** [comment]
@joaomlneto thanks for reply and quick response. I downloaded and used the mpi version a bit yesterday. Its great!! I love a resource like this becuase it is kinda sorta the hello world of numerical libraries.

After considering options, however, I've decided I need to work from a different code base towards a similar goal; 1D heat equation implementations for serial, OMP parallel, MPI parallal, Cuda Parallel, and with performance portability layers like [Raja](https://github.com/LLNL/RAJA), [Kokkos](https://github.com/kokkos/kokkos), Legion, as well incuding [performane counters](http://icl.cs.utk.edu/papi/). This is all part of two parallel efforts to demonstrate and train developers in the use of [ECP project Continuous Integration resources](https://www.exascaleproject.org/project/continuous-integration-testing-release/) and to [train early career developers in the use of numerical libraries](https://xsdk-project.github.io/ATPESC2018HandsOnLessons/lessons/hand_coded_heat/).
